### ISSUE TITLE
Bug: Generating HTML documentation with spectacle

### ISSUE THREAD

**Issue by juleshaas** [actinia-org/actinia-core#368]
**Code:**
https://github.com/mundialis/actinia_core/blob/main/docs/docs/actinia_concepts.md?plain=1

```bash
 # Download the latest swagger definition from the actinia service
 wget  https://actinia.mundialis.de/latest/swagger.json -O /tmp/actinia.json
 # Run spectacle docker image to generate the HTML documentation
 docker run -v /tmp:/tmp -t sourcey/spectacle spectacle /tmp/actinia.json -t /tmp
 # Start Firefox to show the documentation
 firefox /tmp/index.html
```

**Bug:**
The second step results in Error:

```
10:52 $ docker run -v /tmp:/tmp -t sourcey/spectacle spectacle /tmp/actinia.json -t /tmp
request-sync is deprecated, use sync-request
/usr/local/lib/node_modules/spectacle-docs/app/lib/resolve-references.js:169
    if(val.$ref) {
          ^

TypeError: Cannot read property '$ref' of null
    at replaceRefs (/usr/local/lib/node_modules/spectacle-docs/app/lib/resolve-references.js:169:11)
    at replaceRefs (/usr/local/lib/node_modules/spectacle-docs/app/lib/resolve-references.js:189:5)
    at replaceRefs (/usr/local/lib/node_modules/spectacle-docs/app/lib/resolve-references.js:189:5)
    at replaceRefs (/usr/local/lib/node_modules/spectacle-docs/app/lib/resolve-references.js:189:5)
    at replaceRefs (/usr/local/lib/node_modules/spectacle-docs/app/lib/resolve-references.js:189:5)
    at replaceRefs (/usr/local/lib/node_modules/spectacle-docs/app/lib/resolve-references.js:189:5)
    at replaceRefs (/usr/local/lib/node_modules/spectacle-docs/app/lib/resolve-references.js:189:5)
    at replaceRefs (/usr/local/lib/node_modules/spectacle-docs/app/lib/resolve-references.js:189:5)
    at replaceRefs (/usr/local/lib/node_modules/spectacle-docs/app/lib/resolve-references.js:189:5)
    at replaceRefs (/usr/local/lib/node_modules/spectacle-docs/app/lib/resolve-references.js:189:5)
    at replaceRefs (/usr/local/lib/node_modules/spectacle-docs/app/lib/resolve-references.js:189:5)
    at replaceRefs (/usr/local/lib/node_modules/spectacle-docs/app/lib/resolve-references.js:189:5)
    at module.exports (/usr/local/lib/node_modules/spectacle-docs/app/lib/preprocessor.js:76:3)
    at loadData (/usr/local/lib/node_modules/spectacle-docs/index.js:52:72)
    at module.exports (/usr/local/lib/node_modules/spectacle-docs/index.js:56:70)
    at Object.<anonymous> (/usr/local/lib/node_modules/spectacle-docs/bin/spectacle.js:35:1)
```

**Remarks:**
The spectacle rendering differs a bit from the rendering with ReDocly.
In spectacle also models are displayed.
The rendering still works with a  local installation of spectacle and an old version of node.

```
spectacle /tmp/actinia.json -t /tmp
which spectacle
$HOME/.nvm/versions/node/v15.12.0/bin/spectacle
```

 originally posted in #214

**Comment by anikaweinmann** [comment]
If this is fixed try to add a workflow for it.

**Comment by mmacata** [comment]
Closing as there are different options to see api docs
